import type { Metadata } from "next";
import localFont from "next/font/local";
import { SmoothScroll } from "@/components/SmoothScroll";
import Loader from "@/components/Loader";
import "./globals.css";

// Load variable font
const Sat = localFont({
  src: "../fonts/Satoshi-Variable.woff2",
  variable: "--font-sat", // CSS variable
  weight: "400 700", // Range for variable font
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${Sat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScroll>
          <Loader minDurationMs={2000}>{children}</Loader>
        </SmoothScroll>
      </body>
    </html>
  );
}
